### PR TITLE
Hello, Northstar.

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
 - Fixes broken unit tests, and configures Wercker to run unit tests on build. :traffic_light: 
 - Minor cleanup – documentation, code style, etc.

:construction:

### CODE REVIEW

**Comment by angaither** [comment]
AWESOME. :+1: 

ALSO. one thing maybe we should consider is removing the drupal-y id
maybe instead of `sid` and `rbid` it's `signup_id` &  `reportback_id`

cc @jonuy

**Comment by DFurnes** [comment]
That'd make a ton of sense to me. :+1:

**Comment by jonuy** [comment]
Yea, I like that idea. @weerd even started going in that direction too with the reportbacks work he was doing on the Drupal Services side.

**Comment by angaither** [comment]
:cool: :cool: :cool:

**Comment by weerd** [comment]
Yep yep! I'm working on doing some `POST` calls and to pass through data I'm using properties like `user_id`, `reportback_item_id` etc. It just feels like it would be much clearer for devs posting to the API and that are not familiar with Drupal :)

**Comment by DFurnes** [comment]
Removed steps that tried to run PHPUnit tests on Wercker. Seems like something needs to be configured on the box first for MongoDB to work there. :cry: A task for another day!

**Pull request merged**
