### PR TITLE
Prevent editing internal fields from profile endpoint.

### PR DESCRIPTION
**Pull request by DFurnes**
#### What's this PR do?
This pull request prevents users from being able to edit "internal" fields on their profile, such as Drupal ID or Mobile Commons ID. These fields can now only be edited by "trusted" internal applications via the `users/` endpoints.

#### How should this be reviewed?
Review the code & updated test case.

#### Checklist
- [x] Documentation added for changed endpoints.
- [x] Tests added for new features/bug fixes.

---
For review: @angaither

### CODE REVIEW

**Comment by angaither** [comment]
should we also allow `source` to only be internal?

**Comment by angaither** [comment]
oh and maybe `parse_installation_ids`?

**Comment by DFurnes** [comment]
At the moment the mobile app explicitly sends a source & the device's Parse IDs when registering a user, so we need to leave those both accessible. Ideally we could set the source automatically based on the OAuth client ID making the request.

**Comment by DFurnes** [comment]
@angaither Dropped in two more fixes: locked down those fields from the `auth/register` endpoint (35df797, fee579f) and a teeny capitalization fix in an unrelated test (17ff9be).

**Comment by angaither** [comment]
🚢

**Pull request merged**
