### PR TITLE
rename /campaigns to users/campaigns

### LINKED ISSUE #138: Rename /campaigns
This route overlaps with `/campaigns` on drupal
Since we aren't asking for a list of campaigns with this route in NS, let's rename this to `user/campaigns`

### PR DESCRIPTION
**Pull request by chloealee**
Fixes #138 

Rename `/campaigns` to `users/campaigns`

### CODE REVIEW

**Comment by jonuy** [comment]
I slept on the naming of this route and I still feel kinda iffy about it. What about `user-campaigns/`?

With `users/` without a resource id following it, I think it suggests that it should return info for all users. I also wonder if there are any scenarios where this path could be technically problematic since it shares the same name as the main `users` path.

**Comment by aaronschachter** [comment]
`campaign-activity`?  or `activity/campaigns` ?  (later we could have `activity/games`, etc)

**Comment by aaronschachter** [comment]
or just `campaigns` `games` etc

**Comment by DFurnes** [comment]
Another suggestion would be using `user/` as a "resource" for the current authenticated user, and `user/campaigns` for the list of all campaigns. This is how GitHub handles [listing the current user repos vs. a specific user's repos](https://developer.github.com/v3/repos/#list-your-repositories).

**Comment by jonuy** [comment]
Ah, probably why Andrea suggested `user/campaigns` in the first place. oops. That also works if we want to do `user/games` and the like later on.

**Comment by chloealee** [comment]
awesome, thanks! Just changed it to user/campaigns

**Comment by jonuy** [comment]
:+1:

**Comment by DFurnes** [comment]
Makes sense to me! :+1:

**Pull request merged**
