### PR TITLE
Adds New Images to NS Registration Pages

### PR DESCRIPTION
**Pull request by Vmack**
### What's this PR do?

This pull request adds the suggested images to the NS reg pages 

**Welcome Page** Screen Shot 2020-04-30 at 10 52 54 AM

**Profile Page**
Screen Shot 2020-04-30 at 10 55 55 AM

**Subscription Page**
Screen Shot 2020-04-30 at 10 57 26 AM

### How should this be reviewed?

How's the quality of the images? 

[more images ](https://drive.google.com/drive/folders/1CTWkNTcvl_omfIzF0Pm089uiu7lRhw8f)

### Relevant tickets

References [Pivotal #171082025](https://www.pivotaltracker.com/story/show/171082025).

### Checklist

- [ ] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added appropriate feature/unit tests.
- [ ] If new attributes were added to users, there is a corresponding PR to surface these in Aurora.
- [ ] If new attributes were added to users, then the data team already knows about these changes.

### CODE REVIEW

**Comment by katiecrane** [comment]
looks like the right images are in the right places to me but we'll know for sure once we can get some screenshots 👍

**Comment by katiecrane** [comment]
@Vmack the screenshots looks great! would you mind adding some more at some smaller screen sizes to make sure everything is still looking good?

**Comment by Vmack** [comment]
@katiecrane I added more in the "How should this be reviewed?" section

**Comment by katiecrane** [comment]
@Vmack ah I see that now, thank you!

**Pull request merged**
