### PR TITLE
Some adjustments for better concurrency.

### PR DESCRIPTION
**Pull request by DFurnes**
#### What's this PR do?
Adjusting Northstar's nginx & php-fpm settings so we're able to handle load more efficiently.

#### How should this be reviewed?
See load tests below, ran with this branch deployed to [dosomething-northstar-prod](https://dashboard.heroku.com/apps/dosomething-northstar-prod).

#### Relevant Tickets
References DoSomething/devops#427.

#### Checklist
- [ ] Documentation added for changed endpoints.
- [ ] Tests added for new features/bug fixes.
- [ ] Post a message in #api if this includes something that causes a rebuild!

### CODE REVIEW

**Comment by DFurnes** [comment]
Tried deploying this to the new production Heroku instance, and (manually) setting `WEB_CONCURRENCY` to 40 (based on the suggested [defaults](https://devcenter.heroku.com/articles/php-concurrency#web_concurrency-defaults) here w/ halved `memory_limit` from 625403b).

**Comment by DFurnes** [comment]
Following up on load testing from DoSomething/devops#383. This is at `WEB_CONCURRENCY=20`:

```
λ ~ siege -c 100 -t 1M -i -f profiles.txt --header="Authorization: Bearer ******"

** SIEGE 4.0.4
** Preparing 100 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.58 secs:     642 bytes ==> GET  /v2/users/54fa273a469c64d7068b45ca
HTTP/1.1 200     0.60 secs:     643 bytes ==> GET  /v2/users/54fa2752469c64d7068b4665
HTTP/1.1 200     0.62 secs:     638 bytes ==> GET  /v2/users/54fa2747469c64d7068b461d
HTTP/1.1 200     0.70 secs:     657 bytes ==> GET  /v2/users/54fa2746469c64d7068b461a
.....
HTTP/1.1 200     1.90 secs:     645 bytes ==> GET  /v2/users/54fa2749469c64d7068b462c
HTTP/1.1 200     0.09 secs:     631 bytes ==> GET  /v2/users/54fa2736469c64d7068b45b0
HTTP/1.1 200     0.12 secs:     670 bytes ==> GET  /v2/users/54fa2740469c64d8068b45f1
HTTP/1.1 200     0.12 secs:     630 bytes ==> GET  /v2/users/5589c306469c64e3608b6c41
HTTP/1.1 200     0.17 secs:     647 bytes ==> GET  /v2/users/54fa272d469c64d8068b4576
HTTP/1.1 200     2.00 secs:     634 bytes ==> GET  /v2/users/54fa2747469c64d8068b461e

Lifting the server siege...
Transactions:		        4790 hits
Availability:		      100.00 %
Elapsed time:		       59.37 secs
Data transferred:	        2.93 MB
Response time:		        1.22 secs
Transaction rate:	       80.68 trans/sec
Throughput:		        0.05 MB/sec
Concurrency:		       98.07
Successful transactions:        4790
Failed transactions:	           0
Longest transaction:	        4.26
Shortest transaction:	        0.06
```

Still a lot of request queueing in [New Relic's transaction graph](https://user-images.githubusercontent.com/583202/42244282-6a83e9fa-7ee2-11e8-8e66-efc9582742fb.png), though. 🤔

**Comment by sheyd** [comment]
@DFurnes Heroku has a help page about this: https://help.heroku.com/QB0BKTNJ/is-it-normal-for-requests-to-spend-a-long-time-in-request-queuing-as-reported-by-newrelic. They recommend looking at the router `connect` time logs.

**Comment by DFurnes** [comment]
@sheyd I think Request Queueing _is_ what I'm looking for here – I'm specifically curious about requests piling up between the router and php-fpm, since we were previously only letting php-fpm process one request at a time. The `connect` time just reports how much time Heroku's router takes per request.

**Comment by DFurnes** [comment]
I did one more load test at 20 requests/second and `WEB_CONCURRENCY=20`, and [no request queuing](https://user-images.githubusercontent.com/583202/42247235-dfbab680-7eed-11e8-8cff-6fbbb17ddb9c.png):

```
λ ~ siege -c 20 -t 10M -i -f profiles.txt --header="Authorization: Bearer ******"

** SIEGE 4.0.4
** Preparing 20 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.34 secs:     637 bytes ==> GET  /v2/users/54fa2738469c64d7068b45c0
HTTP/1.1 200     0.37 secs:     641 bytes ==> GET  /v2/users/54fa2734469c64d7068b45a0
HTTP/1.1 200     0.40 secs:     664 bytes ==> GET  /v2/users/54fa2732469c64d8068b4598
......
HTTP/1.1 200     0.40 secs:     637 bytes ==> GET  /v2/users/54fa2738469c64d7068b45c0
HTTP/1.1 200     0.40 secs:     656 bytes ==> GET  /v2/users/54fa273b469c64d8068b45d1
HTTP/1.1 200     0.36 secs:     638 bytes ==> GET  /v2/users/54fa2731469c64d8068b458e
HTTP/1.1 200     0.38 secs:     634 bytes ==> GET  /v2/users/54fa2747469c64d8068b461e

Lifting the server siege...
Transactions:		       22514 hits
Availability:		      100.00 %
Elapsed time:		      599.34 secs
Data transferred:	       13.79 MB
Response time:		        0.53 secs
Transaction rate:	       37.56 trans/sec
Throughput:		        0.02 MB/sec
Concurrency:		       19.92
Successful transactions:       22514
Failed transactions:	           0
Longest transaction:	        5.53
Shortest transaction:	        0.13
```

**Comment by DFurnes** [comment]
Adjusted the memory limit down to 32M, which in turn set our `WEB_CONCURRENCY` to 80. I also set our p95 target response time up to 1000ms to try to reduce the maximum number of dynos we spin up under load.

Ran two five minute load tests at 40 concurrent users & 80 concurrent users – in both cases, we seemed to get pretty darn good response times: 0.77s and 0.86s average, 5s and 3s worst case, and [limited request queueing](https://user-images.githubusercontent.com/583202/42338780-ef8454ec-8058-11e8-9652-7f202a592d80.png) ([throughput](https://user-images.githubusercontent.com/583202/42338784-f3cd58fa-8058-11e8-8855-cb8869d2966c.png)) with a max of 3 dynos in use.

Feeling pretty good about this!


```
λ ~ siege -c 40 -t 5M -i -f profiles.txt --header="Authorization: Bearer ******"
** SIEGE 4.0.4
** Preparing 40 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.72 secs:     630 bytes ==> GET  /v2/users/5589c306469c64e3608b6c41
HTTP/1.1 200     0.74 secs:     643 bytes ==> GET  /v2/users/54fa273e469c64d8068b45e3
......
HTTP/1.1 200     0.10 secs:     664 bytes ==> GET  /v2/users/54fa2753469c64d8068b466e
HTTP/1.1 200     0.78 secs:     647 bytes ==> GET  /v2/users/54fa272f469c64d8068b4582
HTTP/1.1 200     0.87 secs:     664 bytes ==> GET  /v2/users/54fa2753469c64d8068b466e

Lifting the server siege...
Transactions:		       15488 hits
Availability:		      100.00 %
Elapsed time:		      299.12 secs
Data transferred:	        9.49 MB
Response time:		        0.77 secs
Transaction rate:	       51.78 trans/sec
Throughput:		        0.03 MB/sec
Concurrency:		       39.92
Successful transactions:       15488
Failed transactions:	           0
Longest transaction:	        5.28
Shortest transaction:	        0.06


λ ~ siege -c 80 -t 5M -i -f profiles.txt --header="Authorization: Bearer ******"
** SIEGE 4.0.4
** Preparing 80 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.87 secs:     628 bytes ==> GET  /v2/users/54fa2747469c64d8068b461c
HTTP/1.1 200     0.85 secs:     626 bytes ==> GET  /v2/users/54fa2739469c64d7068b45c2
HTTP/1.1 200     0.86 secs:     651 bytes ==> GET  /v2/users/54fa2759469c64d7068b4694
......
HTTP/1.1 200     0.11 secs:     640 bytes ==> GET  /v2/users/54fa2734469c64d8068b45a5
HTTP/1.1 200     1.28 secs:     675 bytes ==> GET  /v2/users/54fa2752469c64d8068b4666
HTTP/1.1 200     0.46 secs:     649 bytes ==> GET  /v2/users/54fa2739469c64d7068b45c7

Lifting the server siege...
Transactions:		       27588 hits
Availability:		      100.00 %
Elapsed time:		      299.03 secs
Data transferred:	       16.90 MB
Response time:		        0.86 secs
Transaction rate:	       92.26 trans/sec
Throughput:		        0.06 MB/sec
Concurrency:		       79.80
Successful transactions:       27588
Failed transactions:	           0
Longest transaction:	        3.34
Shortest transaction:	        0.06
```

And auto-scaling during these two load tests:

```
Jul 05 13:20:21 dosomething-northstar-prod app/api: Scaled to web@1:Performance-M by user metrics-team+apphs@heroku.com 
Jul 05 13:21:00 --------- Began load test w/ 40 concurrent users. ---------
Jul 05 13:25:21 dosomething-northstar-prod app/api: Scaled to web@2:Performance-M by user metrics-team+apphs@heroku.com 
Jul 05 13:26:00 --------- Ended load test w/ 40 concurrent users. ---------
Jul 05 13:26:00 --------- Began load test w/ 80 concurrent users. ---------
Jul 05 13:31:15 dosomething-northstar-prod app/api: Scaled to web@3:Performance-M by user metrics-team+apphs@heroku.com 
Jul 05 13:31:00 --------- Ended load test w/ 80 concurrent users. ---------
Jul 05 13:38:27 dosomething-northstar-prod app/api: Scaled to web@2:Performance-M by user metrics-team+apphs@heroku.com 
Jul 05 13:42:15 dosomething-northstar-prod app/api: Scaled to web@1:Performance-M by user metrics-team+apphs@heroku.com 
```

**Pull request merged**
