### PR TITLE
Upgrade to Laravel 5.

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
 - Laravel 5.

For review: @angaither @jonuy

### CODE REVIEW

**Comment by DFurnes** [comment]
Discussion question: do we want to switch to using PSR-2 indentation (four-space), since that's what Laravel will be using once 5.1 is released?

**Comment by jonuy** [comment]
ooo they're leaving the tabs behind and moving onto spaces? I'm for switching to PSR-2 if we think we'll also make the upgrade to 5.1. It could make our diff history a little ugly, but it'll bring consistency across core Laravel code and ours.

**Comment by DFurnes** [comment]
Cool cool, reformatted to PSR-2 indentation & updated contribution guidelines.

**Comment by weerd** [comment]
Files changes `132` :scream: haha

**Comment by DFurnes** [comment]
:smirk:

**Pull request merged**
