### PR TITLE
Run composer update

### PR DESCRIPTION
**Pull request by katiecrane**
#### What's this PR do?
Just ran `composer update` and included the updated `composer.lock` file.

#### How should this be reviewed?
👀 

#### Relevant Tickets
[Card](https://www.pivotaltracker.com/story/show/157288532)

#### Checklist
- [ ] Documentation added for changed endpoints.
- [ ] Tests added for new features/bug fixes.
- [ ] Post a message in #api if this includes something that causes a rebuild!

### CODE REVIEW

**Comment by DFurnes** [comment]
We can do this in a separate pull request, but we should also upgrade `oauth2-server` to the [latest release](https://github.com/thephpleague/oauth2-server/blob/master/CHANGELOG.md#710---released-2018-04-22). We're still on 6.x, but luckily looks like the only breaking change is dropping old PHP support.

**Comment by katiecrane** [comment]
@DFurnes would that be to update to `~7.0.0`? And would that require any additional testing?

**Comment by DFurnes** [comment]
I think it'd be a good idea to set our constraint to `^7.0.0` so we get minor updates as well when we run `composer update` (like `7.1.0`, which is the current latest release).

**Comment by DFurnes** [comment]
As long as the test suite passes, I think we should be safe to update.

**Comment by katiecrane** [comment]
@DFurnes I tried updating locally and tests are failing 😩 
```
vagrant@homestead:~/Sites/northstar$ vendor/bin/phpunit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

........................PHP Fatal error:  Declaration of Northstar\Auth\Repositories\ClientRepository::getClientEntity($clientIdentifier, $grantType, $clientSecret = NULL, $mustValidateSecret = true) must be compatible with League\OAuth2\Server\Repositories\ClientRepositoryInterface::getClientEntity($clientIdentifier, $grantType = NULL, $clientSecret = NULL, $mustValidateSecret = true) in /home/vagrant/Sites/northstar/app/Auth/Repositories/ClientRepository.php on line 9
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/Sites/northstar/vendor/laravel/framework/src/Illuminate/Container/Container.php:918
```

**Comment by DFurnes** [comment]
If you update that `getClientEntity` to have the default value `= NULL` for `$clientSecret`, does that clear up the test failures?

**Comment by katiecrane** [comment]
@DFurnes ah I think it was `$grantType = null` that was missing (we had no default before). But one test is still failing:
```
1) OAuthTest::testAuthorizationCodeGrant
Expected status code 200, got 400.
Failed asserting that 400 matches expected 200.

/home/vagrant/Sites/northstar/vendor/laravel/browser-kit-testing/src/Concerns/MakesHttpRequests.php:744
/home/vagrant/Sites/northstar/tests/Http/OAuthTest.php:17
/home/vagrant/Sites/northstar/tests/Http/OAuthTest.php:78
```

**Comment by DFurnes** [comment]
Oh oof yeah, that's the one I meant! I can swing by if you want to dig into that `OAuthTest` failure.

**Pull request merged**
