### PR TITLE
Return the full reportback object from the store endpoint.

### PR DESCRIPTION
**Pull request by DFurnes**
### Changes
References #281. This is a temporary measure until we can update the underlying API on Phoenix!

:warning: __Breaking Change:__ The `POST /reportbacks` endpoint will now return a full reportback object (same formatting as the `GET /reportbacks/:id` endpoint), rather than an array with a string ID.

:warning: __Breaking Change:__ The `POST /signups` endpoint will now return a full signup object (same formatting as the `GET /signups/:id` endpoint), rather than an array with a string ID.

### Discussion
~~For the signup endpoint, I'm not sure whether I _can_ fetch the existing signup... I tried fetching signups from the `signups/` endpoint with the proper `?user=xxx` and `&campaign=xxx` filter parameters, but it ended up returning like 5 campaigns. :disappointed: 

This might be a campaign-run issue...? Not 100% sure but would love thoughts if anyone has them.~~

Okay, never mind! I was passing a single `campaign=123` rather than `campaigns=123` and I am very dumb so never mind anything okay bye.

---
For review: @weerd @angaither 
/cc @jonuy @aaronschachter

### CODE REVIEW

**Comment by DFurnes** [comment]
Woohoo, with the changes in DoSomething/phoenix#6174 the `GET /reportbacks/:id` is now working for newly-submitted reportbacks! :tada:

**Comment by weerd** [comment]
yay! :dancers:

**Comment by weerd** [comment]
:+1:

**Comment by DFurnes** [comment]
And was able to fix the issue I'd been having with fetching an existing signup. Hackzzzz! :muscle:

**Comment by weerd** [comment]
:+1: :dancer:

**Pull request merged**
