### PR TITLE
Adds school_id field

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?

Adds a `school_id` text field to be used by the School Finder component in Phoenix (https://github.com/DoSomething/phoenix-next/pull/1668)

#### How should this be reviewed?
👀 

#### Relevant Tickets

https://www.pivotaltracker.com/n/projects/2401401/stories/169294661/

#### Checklist
- [ ] Documentation added for changed endpoints.
- [ ] Tests added for new features/bug fixes.
- [ ] Post a message in #api if this includes something that causes a rebuild!

### CODE REVIEW

**Comment by aaronschachter** [comment]
That's correct! We'll save the Great Schools `gsid` as the user `school_id` if they select a school, and save a string like `not-available` if they are unable to find their school in the dropdown.

**Comment by mshmsh5000** [comment]
Here's a database view:

Image 2019-10-31 at 11 59 59 AM

**Comment by aaronschachter** [comment]
I've been assuming we should save `gs-id`, as we've historically done. Universal ID is a new player in the mix, do you think we're ok with sticking with `gs-id` @mshmsh5000 ?

**Comment by mshmsh5000** [comment]
In the Great Schools data dictionary, `gs-id` is

>Unique within each state; also included in GreatSchools' school/district overview page URL string

whereas `universal-id` seems to be unique within the GS data set:

>ID for data matching between feed products

The full data dictionary is on the Shared Drive: Data -> Vendors -> Great Schools -> 2019-10

**Pull request merged**
